### ISSUE TITLE
Mobile | Android | Your Info - Continue button shows behind the input fields

### ISSUE THREAD

**Issue by joeyqa** [tooldigital/pandora-sly-p2#9]
After entering valid inputs, notice that the continue button shows behind the input fields.

**Expected Result:**
- The button should appear below the form.

**Browser / Device info:**
- Galaxy S6 (6.0)   - Native 6.4.10.5
- Pixel XL (7.1.2)  - Chrome 66

**URL:**
- http://soundslikeyoudev.seethroughlab.com/#!/your-info

**Steps:**
1. Load the URL.
2. Tap the TAP TO BEGIN button.
3. Enter valid input to the fields.
4. Verify that the continue button shows on below the input fields.

Please see the attached screenshot(s): https://goo.gl/7iWCis

**Comment by wearenocomputer** [comment]
Implemented a fix for this, but needs to be tested on an actual device (I have no access to the devices mentioned). So please re-test/validate/provide feedback...

**Comment by jonathanschaefferhookqa** [comment]
Can verify this is now fixed on Android devices.

**Comment by VJDY** [comment]
Please reopen this. Looks like the issue still persists on Pixel XL and Galaxy S6. Thanks. 
https://goo.gl/N2Xw6Q
